### ISSUE TITLE
Responses import fails

### ISSUE THREAD

**Issue by znat** [botfront/botfront#20]
**Describe the bug**
See title

**To Reproduce**
Import bot responses

```
botfront_1      | Exception while invoking method 'templates.import' ReferenceError: Match is not defined
botfront_1      |     at MethodInvocation.templates.import (imports/api/project/response.methods.js:107:30)
botfront_1      |     at currentArgumentChecker.withValue (packages/check/match.js:118:15)
botfront_1      |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
botfront_1      |     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
botfront_1      |     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1764:18)
botfront_1      |     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
botfront_1      |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
botfront_1      |     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
botfront_1      |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
botfront_1      |     at Promise (packages/ddp-server/livedata_server.js:715:46)
botfront_1      |     at new Promise (<anonymous>)
botfront_1      |     at Session.method (packages/ddp-server/livedata_server.js:689:23)
botfront_1      |     at packages/ddp-server/livedata_server.js:559:43
```

**Comment by MatthieuJnon** [comment]
Thanks for the heads up, currently fixing and adding tests
