### ISSUE TITLE
Overlapping Entities

### ISSUE THREAD

**Issue by aintHuman** [botfront/botfront#249]
Running botfront 0.16.0-rc.12

Trying to evaluate my model, via the `NLU > Evaluation` page, the following error is thrown.

```
botfront-rasa   | 2019-10-09 07:42:06 INFO     rasa.nlu.test  - Entity evaluation results:
botfront-rasa   | 2019-10-09 07:42:06 WARNING  rasa.nlu.test  - Overlapping entity {'start': 9, 'end': 19, 'value': '0490123456', 'entity': 'phone-number'} with {'start': 9, 'end': 19, 'value': '0490123456', 'entity': 'number'}
botfront-rasa   | 2019-10-09 07:42:06 DEBUG    rasa.server  - Traceback (most recent call last):
botfront-rasa   |   File "/usr/local/lib/python3.6/site-packages/rasa/server.py", line 801, in evaluate_intents
botfront-rasa   |     evaluation = run_evaluation(data_path, nlu_models.get(language))
botfront-rasa   |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/test.py", line 1063, in run_evaluation
botfront-rasa   |     entity_results, extractors, output_directory, successes, errors
botfront-rasa   |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/test.py", line 636, in evaluate_entities
botfront-rasa   |     aligned_predictions = align_all_entity_predictions(entity_results, extractors)
botfront-rasa   |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/test.py", line 856, in align_all_entity_predictions
botfront-rasa   |     aligned_predictions.append(align_entity_predictions(result, extractors))
botfront-rasa   |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/test.py", line 833, in align_entity_predictions
botfront-rasa   |     true_token_labels.append(determine_token_labels(t, result.entity_targets, None))
botfront-rasa   |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/test.py", line 794, in determine_token_labels
botfront-rasa   |     raise ValueError("The possible entities should not overlap")
botfront-rasa   | ValueError: The possible entities should not overlap
botfront-rasa   |
```

I believe this is an issue with the interpretation of output from the duckling server, because two duckling entities (such as `phone-number`, and `number`), can, and often will overlap in terms of the positioning:

**Overlapping entity {'start': 9, 'end': 19, 'value': '0490123456', 'entity': 'phone-number'} with {'start': 9, 'end': 19, 'value': '0490123456', 'entity': 'number'}**

**Comment by znat** [comment]
This is a regression. Duckling entities should be excluded from evaluation. We should only keep trainable entities (ner_crf extractor)

**Comment by nickhamilton1980** [comment]
Thanks, so have I performed the evaluation incorrectly? These entities are part of my training data, or is that incorrect too?

**Comment by znat** [comment]
No, it's a bug in our end. We shouldn't evaluate Duckling entities since Duckling is deterministic. Until we fix it you can comment the duckling part in your pipeline when training for evaluation.

**Comment by nickhamilton1980** [comment]
Ok Rojer that. Cheers.
