### ISSUE TITLE
Menu option "show logs" throws typeError

### ISSUE THREAD

**Issue by GeovanaRamos** [botfront/botfront#338]
**Describe the bug**
After selecting option "Show logs" on botfront menu a TypeError is thrown. Tested in two different computers.

```
TypeError: Cannot read property 'ci' of undefined
    at Object.dockerComposeFollow [as cmd] (/home/geovana/.nvm/versions/node/v13.2.0/lib/node_modules/botfront/src/commands/services.js:184:39)
    at general (/home/geovana/.nvm/versions/node/v13.2.0/lib/node_modules/botfront/src/cli.js:175:47)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) 
```

**To Reproduce**
1. Go to your project's folder
2. Run "botfront" on shell
3. Select "Show logs"

**Comment by znat** [comment]
Fixed on master
