### ISSUE TITLE
Error while running e2e

### ISSUE THREAD

**Issue by engahmed1190** [botfront/botfront#470]
**Describe the bug**
```
botfront-test-rasa | Traceback (most recent call last):
botfront-test-rasa |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 60, in _create_single_channel
botfront-test-rasa |     input_channel_class = rasa.utils.common.class_from_module_path(channel)
botfront-test-rasa |   File "/usr/local/lib/python3.6/site-packages/rasa/utils/common.py", line 193, in class_from_module_path
botfront-test-rasa |     raise ImportError(f"Cannot retrieve class from path {module_path}.")
botfront-test-rasa | ImportError: Cannot retrieve class from path code.
botfront-test-rasa | 
botfront-test-rasa | During handling of the above exception, another exception occurred:
botfront-test-rasa | 
botfront-test-rasa | Traceback (most recent call last):
botfront-test-rasa |   File "/usr/local/bin/rasa", line 8, in <module>
botfront-test-rasa |     sys.exit(main())
botfront-test-rasa |   File "/usr/local/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
botfront-test-rasa |     cmdline_arguments.func(cmdline_arguments)
botfront-test-rasa |   File "/usr/local/lib/python3.6/site-packages/rasa/cli/run.py", line 87, in run
botfront-test-rasa |     rasa.run(**vars(args))
botfront-test-rasa |   File "/usr/local/lib/python3.6/site-packages/rasa/run.py", line 56, in run
botfront-test-rasa |     **kwargs,
botfront-test-rasa |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 162, in serve_application
botfront-test-rasa |     input_channels = create_http_input_channels(channel, credentials)
botfront-test-rasa |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 49, in create_http_input_channels
botfront-test-rasa |     return [_create_single_channel(c, k) for c, k in all_credentials.items()]
botfront-test-rasa |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 49, in <listcomp>
botfront-test-rasa |     return [_create_single_channel(c, k) for c, k in all_credentials.items()]
botfront-test-rasa |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 68, in _create_single_channel
botfront-test-rasa |     "is a proper name of a class in a module.".format(channel)
botfront-test-rasa | Exception: Failed to find input channel class for 'code'. Unknown input channel. Check your credentials configuration to make sure the mentioned channel is not misspelled. If you are creating your own channel, make sure it is a proper name of a class in a module.
```

**To Reproduce**
```
docker-compose up \
          --abort-on-container-exit \
          --exit-code-from e2e
```

**Comment by pheel** [comment]
@engahmed1190 What are you credentials (Settings > Credentials)?
