### ISSUE TITLE
meteor app doesn't start

### ISSUE THREAD

**Issue by dcsan** [botfront/botfront#495]
**Describe the bug**
checked out the main botfront repo
start with

`meteor npm run start:docker-compose.dev`

```
▶ meteor npm run start:docker-compose.dev

> botfront@0.19.3 start:docker-compose.dev /Users/dcollier/dev/rnd/botfront/botfront
> MODE=development BF_PROJECT_ID=bf MONGO_URL=mongodb://localhost:27017/bf ORCHESTRATOR=docker-compose meteor run

[[[[[ ~/dev/rnd/botfront/botfront ]]]]]

=> Started proxy.

Unable to resolve some modules:

  "perf_hooks" in /Users/dcollier/dev/rnd/botfront/botfront/imports/api/instances/instances.methods.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save meteor-node-stubs


Unable to resolve some modules:

  "perf_hooks" in /Users/dcollier/dev/rnd/botfront/botfront/imports/api/instances/instances.methods.js (web.browser.legacy)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save meteor-node-stubs

=> Meteor 1.9.2 is available. Update this project with 'meteor update'.
W20200227-11:17:38.003(-8)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20200227-11:17:38.056(-8)? (STDERR) While this implementation will work correctly, it is known to be
W20200227-11:17:38.057(-8)? (STDERR) approximately three times slower than the native implementation.
W20200227-11:17:38.057(-8)? (STDERR) In order to use the native implementation instead, run
W20200227-11:17:38.057(-8)? (STDERR)
W20200227-11:17:38.057(-8)? (STDERR)   meteor npm install --save bcrypt
W20200227-11:17:38.058(-8)? (STDERR)
W20200227-11:17:38.058(-8)? (STDERR) in the root directory of your application.
W20200227-11:17:38.058(-8)? (STDERR) /Users/dcollier/.meteor/packages/meteor-tool/.1.8.1.kdfmnh.a1fyq++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:313
W20200227-11:17:38.058(-8)? (STDERR) 						throw(ex);
W20200227-11:17:38.059(-8)? (STDERR) 						^
W20200227-11:17:38.059(-8)? (STDERR)
W20200227-11:17:38.059(-8)? (STDERR) MongoError: command listIndexes requires authentication
W20200227-11:17:38.059(-8)? (STDERR)     at /Users/dcollier/.meteor/packages/npm-mongo/.3.1.2.txmpy4.sr35++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:581:63
W20200227-11:17:38.059(-8)? (STDERR)     at authenticateStragglers (/Users/dcollier/.meteor/packages/npm-mongo/.3.1.2.txmpy4.sr35++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:504:16)
W20200227-11:17:38.060(-8)? (STDERR)     at Connection.messageHandler (/Users/dcollier/.meteor/packages/npm-mongo/.3.1.2.txmpy4.sr35++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:540:5)
W20200227-11:17:38.060(-8)? (STDERR)     at emitMessageHandler (/Users/dcollier/.meteor/packages/npm-mongo/.3.1.2.txmpy4.sr35++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/connection.js:310:10)
W20200227-11:17:38.060(-8)? (STDERR)     at Socket.<anonymous> (/Users/dcollier/.meteor/packages/npm-mongo/.3.1.2.txmpy4.sr35++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/connection.js:453:17)
W20200227-11:17:38.060(-8)? (STDERR)     at emitOne (events.js:116:13)
W20200227-11:17:38.060(-8)? (STDERR)     at Socket.emit (events.js:211:7)
W20200227-11:17:38.061(-8)? (STDERR)     at addChunk (_stream_readable.js:263:12)
W20200227-11:17:38.061(-8)? (STDERR)     at readableAddChunk (_stream_readable.js:250:11)
W20200227-11:17:38.061(-8)? (STDERR)     at Socket.Readable.push (_stream_readable.js:208:10)
W20200227-11:17:38.061(-8)? (STDERR)     at TCP.onread (net.js:601:20)
=> Exited with code: 1

```

gonna try a fresh install of meteor.
as far as i remember, it has it's own install of mongoDB, so not sure how the permissions would be messed up on that...

**Comment by dcsan** [comment]
so this is a meteor or npm issue, but just FYI

```
▶ meteor npm install --save meteor-node-stubs

> sse4_crc32@6.0.1 install /Users/dcollier/dev/rnd/botfront/botfront/node_modules/sse4_crc32
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/dcollier/.meteor/packages/meteor-tool/.1.8.1.kdfmnh.a1fyq++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/Users/dcollier/.meteor/packages/meteor-tool/.1.8.1.kdfmnh.a1fyq++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/dcollier/.meteor/packages/meteor-tool/.1.8.1.kdfmnh.a1fyq++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dcollier/dev/rnd/botfront/botfront/node_modules/sse4_crc32
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN ws@7.2.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-immutable-proptypes@2.1.0 requires a peer of immutable@>=3.6.2 but none is installed. You must install peer dependencies yourself.
npm WARN ts-pnp@1.1.4 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN botfront@0.19.3 No description
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sse4_crc32@6.0.1 (node_modules/sse4_crc32):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sse4_crc32@6.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ meteor-node-stubs@0.4.1
updated 1 package and audited 44515 packages in 11.4s
found 10 vulnerabilities (2 low, 5 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details

rnd/botfront/botfront  master ✗                                                                                                                                         1d ⚑
▶ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by dcsan** [comment]
node-gyp. using python to compile c for JS for meteor >.<

```

rnd/botfront/botfront  master ✗                                                                                                                                        1d ⚑  ⍉
▶ clang --version
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

rnd/botfront/botfront  master ✗                                                                                                                                         1d ⚑
▶ make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

rnd/botfront/botfront  master ✗                                                                                                                                         1d ⚑
▶ python -V
Python 2.7.16

rnd/botfront/botfront  master ✗                                                                                                                                         1d ⚑
▶
```
