### ISSUE TITLE
meteor app - mongo errors?

### ISSUE THREAD

**Issue by dcsan** [botfront/botfront#498]
**Describe the bug**
rel #399 
On starting the meteor app from `botfront/botfront` I see mongo errors in the console

```
W20200229-13:14:56.874(-8)? (STDERR) MongoError: command listIndexes requires authentication
W20200229-13:14:56.874(-8)? (STDERR)     at /Users/dcollier/.meteor/packages/npm-mongo/.3.1.2.txmpy4.sr35++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:581:63
```

https://docs.mongodb.com/manual/reference/command/listIndexes/#required-access
> To run listIndexes when access control is enforced, users must have privileges to listIndexes.

To solve this I installed mongo locally using brew and ran it with

> brew services start mongodb-community

then I'm able to start the meteor app succesfully.
bonus I can login to meteor easily

```
> show dbs
admin   0.000GB
bf      0.001GB
config  0.000GB
local   0.000GB
> use bf
switched to db bf
> show collections
activity
admin_settings
botResponses
...
```

So it seems the mongo that is bundled with your meteor app has problems

**Comment by dcsan** [comment]
updated to v20 rc2

```
commit 78743bb9b076a85523ca1a9be27f3f796ba2081b (HEAD -> master, tag: v0.20.0-rc.2, upstream/master, origin/master, origin/HEAD)
```

now I get a different mongo error

```
W20200229-13:50:00.703(-8)? (STDERR) MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
W20200229-13:50:00.703(-8)? (STDERR)     at Pool.<anonymous> (/Users/dcollier/.meteor/packages/npm-mongo/.3.1.2.txmpy4.sr35++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/topologies/server.js:564:11)
W20200229-13:50:00.703(-8)? (STDERR)     at emitOne (events.js:116:13)

```

For app development I think it's better to run a standalone mongo anyway but maybe the docs should note that?
