### ISSUE TITLE
Telegram  AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by alebeta90** [botfront/botfront#517]
**Describe the bug**
When connecting bot to telegram, it present this error

The bot was working for some time, but somehow it stopped after few minutes and is giving that error

2020-03-18 17:33:28 DEBUG    telegram.bot  - Entering: get_me
2020-03-18 17:33:28 DEBUG    telegram.vendor.ptb_urllib3.urllib3.connectionpool  - https://api.telegram.org:443 "GET /bot1128622398:XXXXXXXXX/getMe HTTP/1.1" 200 197
2020-03-18 17:33:28 DEBUG    telegram.bot  - {'id': 1128622398, 'first_name': 'XXXXbot', 'is_bot': True, 'username': 'XXXXXXbot'}
2020-03-18 17:33:28 DEBUG    telegram.bot  - Exiting: get_me
[2020-03-18 17:33:28 +0000] [1] [ERROR] Exception occurred while handling uri: 'http://example.com/webhooks/telegram/webhook'
Traceback (most recent call last):
  File "/build/lib/python3.6/site-packages/sanic/app.py", line 942, in handle_request
    response = await response
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/build/lib/python3.6/site-packages/rasa/core/channels/telegram.py", line 215, in message
    if self._is_user_message(msg):
  File "/build/lib/python3.6/site-packages/rasa/core/channels/telegram.py", line 175, in _is_user_message
    return message.text is not None
AttributeError: 'NoneType' object has no attribute 'text'

**To Reproduce**
Configure with Telegram channel, following Rasa documentation

**Expected behavior**
Bot will reply

**Comment by alebeta90** [comment]
Hi,

I was checking the logs, and realize that when the bot is flooding the chat, it shows the message:
`Failed to acquire lock for conversation ID <conversation_id>. Retrying...`

I tested trying the LockStore, but it didn't make any difference

**Comment by znat** [comment]
Can you share the credentials and the message you were trying to send?

**Comment by alebeta90** [comment]
Hi Nathan,

Suddenly yesterday all started working again. It is possible, there was an error from Telegram API?

I will close the issue because it is not existent anymore.

thanks

**Comment by mkurilov** [comment]
I've struggled with exactly the same issue described by alebeta90. I beleive the error occured if is unconsistancy between intents and actions which leads to `Couldn't create message for response action 'utter_ХХХ'.` error message while debugging it via `rasa shell`. So that the message variable could be `None` when calling `_is_user_message`.

The solution that works for me is to modify telegram.py script lines 169-175 the following way:
`
    @staticmethod
    def _is_location(message) -> bool:
        return message is not null and message.location is not None

    @staticmethod
    def _is_user_message(message) -> bool:
        return message is not null and message.text is not None
`
