### ISSUE TITLE
HTTP Error 413: Payload Too Large PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by alebeta90** [botfront/botfront#536]
**Describe the bug**
When we are in the middle of the conversation we receive answer as utters names, for example utter_hello instead of receiving the message "Hello" itself.

Rasa Version: rasa-for-botfront-1.7.1-bf4
Botfront: 0.21.3

This is the error from Rasa instance:

```
2020-03-27 10:47:59 DEBUG    rasa.core.processor  - Predicted next action 'utter_Ikbuu_Rur' with confidence 1.00.
2020-03-27 10:47:59 DEBUG    rasa_addons.core.nlg.graphql  - Requesting NLG for utter_Ikbuu_Rur from http://sah-botfront:3000/graphql.
2020-03-27 10:47:59 DEBUG    sgqlc.endpoint.http  - Query:
query(
    $template: StringOrListOfStrings!
    $arguments: Any
    $tracker: ConversationInput
    $channel: NlgRequestChannel
) {
    getResponse(
        template: $template
        arguments: $arguments
        tracker: $tracker
        channel: $channel
    ) {
text
        metadata
        ...on QuickReplyPayload { buttons { title, type, ...on WebUrlButton { url } ...on PostbackButton { payload } } }
        ...on ImagePayload { image }
        ...on CustomPayload { buttons { title, type, ...on WebUrlButton { url } ...on PostbackButton { payload } }, elements, attachment, image, custom }
    }
}
2020-03-27 10:47:59 ERROR    sgqlc.endpoint.http  - http://sah-botfront:3000/graphql: HTTP Error 413: Payload Too Large
2020-03-27 10:47:59 INFO     sgqlc.endpoint.http  - Response header: Access-Control-Allow-Origin: *
2020-03-27 10:47:59 INFO     sgqlc.endpoint.http  - Response header: Connection: close
2020-03-27 10:47:59 INFO     sgqlc.endpoint.http  - Response header: Content-Length: 144
2020-03-27 10:47:59 INFO     sgqlc.endpoint.http  - Response header: Content-Security-Policy: default-src 'self'
2020-03-27 10:47:59 INFO     sgqlc.endpoint.http  - Response header: Content-Type: text/html; charset=utf-8
2020-03-27 10:47:59 INFO     sgqlc.endpoint.http  - Response header: Date: Fri, 27 Mar 2020 10:47:59 GMT
2020-03-27 10:47:59 INFO     sgqlc.endpoint.http  - Response header: Vary: Accept-Encoding
2020-03-27 10:47:59 INFO     sgqlc.endpoint.http  - Response header: X-Content-Type-Options: nosniff
2020-03-27 10:47:59 INFO     sgqlc.endpoint.http  - Response [text/html; charset=utf-8]:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Payload Too Large</pre>
</body>
</html>
2020-03-27 10:47:59 ERROR    rasa_addons.core.nlg.graphql  - NLG web endpoint returned an invalid response: 'NoneType' object is not subscriptable
2020-03-27 10:47:59 DEBUG    rasa.core.processor  - Action 'utter_Ikbuu_Rur' ended with events '[BotUttered('utter_Ikbuu_Rur', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1585306079.54703)]'.
```

Botfront GraphQL logs:

``` bash

2020-03-27T09:55:39.899Z [info] : PUT at http://sah-rasa:5005/model succeeded user: 33N4pWyaeNFWqdZ5s /imports/api/instances/instances.methods.js - rasa.train with {"projectId":"bf","instance":{"_id":"9e693b5a-8311-44b1-b2ba-005965fe98a6","name":"Default Instance","host":"http://sah-rasa:5005","projectId":"bf"}} 204 url: http://sah-rasa:5005/model   
PayloadTooLargeError: request entity too large
    at readStream (/opt/bundle/bundle/programs/server/npm/node_modules/raw-body/index.js:155:17)
    at getRawBody (/opt/bundle/bundle/programs/server/npm/node_modules/raw-body/index.js:108:12)
    at read (/opt/bundle/bundle/programs/server/npm/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/opt/bundle/bundle/programs/server/npm/node_modules/body-parser/lib/types/json.js:135:5)
    at Layer.handle [as handle_request] (/opt/bundle/bundle/programs/server/npm/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/bundle/bundle/programs/server/npm/node_modules/express/lib/router/index.js:317:13)
    at /opt/bundle/bundle/programs/server/npm/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/bundle/bundle/programs/server/npm/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/bundle/bundle/programs/server/npm/node_modules/express/lib/router/index.js:275:10)
    at cors (/opt/bundle/bundle/programs/server/npm/node_modules/cors/lib/index.js:188:7)
    at /opt/bundle/bundle/programs/server/npm/node_modules/cors/lib/index.js:224:17
    at originCallback (/opt/bundle/bundle/programs/server/npm/node_modules/cors/lib/index.js:214:15)
    at /opt/bundle/bundle/programs/server/npm/node_modules/cors/lib/index.js:219:13
    at optionsCallback (/opt/bundle/bundle/programs/server/npm/node_modules/cors/lib/index.js:199:9)
    at corsMiddleware (/opt/bundle/bundle/programs/server/npm/node_modules/cors/lib/index.js:204:7)
    at Layer.handle [as handle_request] (/opt/bundle/bundle/programs/server/npm/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/bundle/bundle/programs/server/npm/node_modules/express/lib/router/index.js:317:13)
    at /opt/bundle/bundle/programs/server/npm/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/bundle/bundle/programs/server/npm/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/bundle/bundle/programs/server/npm/node_modules/express/lib/router/index.js:275:10)
    at promiseWillStart.then (/opt/bundle/bundle/programs/server/npm/node_modules/apollo-server-express/dist/ApolloServer.js:85:41)
    at /opt/bundle/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

**To Reproduce**

Write a long a conversation to create big payloads

**Expected behavior**
Return the reponse text

**Comment by alebeta90** [comment]
Hi friends,

There is a quick fix for this?

I already read some information regarding this issue, it seems we need to modify the BodyParser in order to accept bigger HTTP Body request

all the best

**Comment by pheel** [comment]
Hi @alebeta90,
As you can [see here](https://github.com/expressjs/body-parser#limit), the default is 100kb. It's hard for me to imagine a bot response over 100kb, but if you can confirm a use for this, we can add an environment variable setting.

**Comment by pheel** [comment]
If you're working with the code, the quick fix is to add `bodyParserConfig: { limit: '50mb' }` to `server.applyMiddleware`'s argument in server/apollo.js.

**Comment by alebeta90** [comment]
Hi @pheel thank you very much for your useful answer. 

Yes by any reason the response is being over 100kb, this is why we get that error. Dont know if you may like to receive additional information. 

It would be good if the fix could come from you directly, just to avoid from our side to maintain the image. But if it is not possible we could code it. 

Let us know what is the best solution for all.

All the best

**Comment by pheel** [comment]
No problem, stay posted for next release.

**Comment by pheel** [comment]
Implemented here: https://github.com/botfront/botfront/pull/540.
