### ISSUE TITLE
I got error: Error: Request body larger than maxBodyLength limit when try to training data.

### ISSUE THREAD

**Issue by nhha1602** [botfront/botfront#561]
Dear All,

I got following error when I try to training data: Error: Request body larger than maxBodyLength limit

Could you, please help to to show me how to fix it?

I found in /opt/bundle/bundle/programs/server/npm/node_modules/follow-redirects/index.js:

var exports = {
    maxRedirects: 21,
    maxBodyLength: 10 * 1024 * 1024,
  };

^[[32mbotfront-app    |^[[0m 2020-04-14T03:17:46.822Z [^[[31merror^[[39m] : POST at http://rasa:5005/data/convert/ failed at response time user: qNTKoLTybm62HDgYy /imports/api/instances/instances.methods.js - rasa.getTrainingPayload with {"projectId":"bf","instance":{"_id":"mhHttGKJoLZvWJNj9","name":"Default Instance","host":"http://rasa:5005","projectId":"bf"},"language":""} url: http://rasa:5005/data/convert/  data: "Too much data." error: Error: Request body larger than maxBodyLength limit
^[[32mbotfront-app    |^[[0m 2020-04-14T03:17:47.102Z [^[[31merror^[[39m] : Building training payload failed - 1416.41 ms user: qNTKoLTybm62HDgYy /imports/api/instances/instances.methods.js - rasa.getTrainingPayload with {"projectId":"bf","instance":{"_id":"mhHttGKJoLZvWJNj9","name":"Default Instance","host":"http://rasa:5005","projectId":"bf"},"language":""}
^[[32mbotfront-app    |^[[0m { Error: Request body larger than maxBodyLength limit
^[[32mbotfront-app    |^[[0m     at RedirectableRequest.write (/opt/bundle/bundle/programs/server/npm/node_modules/follow-redirects/index.js:97:24)
^[[32mbotfront-app    |^[[0m     at RedirectableRequest.end (/opt/bundle/bundle/programs/server/npm/node_modules/follow-redirects/index.js:116:8)
^[[32mbotfront-app    |^[[0m     at dispatchHttpRequest (/opt/bundle/bundle/programs/server/npm/node_modules/axios/lib/adapters/http.js:272:11)
^[[32mbotfront-app    |^[[0m     at new Promise (<anonymous>)
^[[32mbotfront-app    |^[[0m     at httpAdapter (/opt/bundle/bundle/programs/server/npm/node_modules/axios/lib/adapters/http.js:20:10)
^[[32mbotfront-app    |^[[0m     at dispatchRequest (/opt/bundle/bundle/programs/server/npm/node_modules/axios/lib/core/dispatchRequest.js:59:10)
^[[32mbotfront-app    |^[[0m     at /opt/bundle/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
^[[32mbotfront-app    |^[[0m  => awaited here:
^[[32mbotfront-app    |^[[0m     at Function.Promise.await (/opt/bundle/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
^[[32mbotfront-app    |^[[0m     at Promise.asyncApply (imports/api/instances/instances.methods.js:231:27)
^[[32mbotfront-app    |^[[0m     at /opt/bundle/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
^[[32mbotfront-app    |^[[0m   config:
^[[32mbotfront-app    |^[[0m    { url: 'http://rasa:5005/data/convert/',
^[[32mbotfront-app    |^[[0m      method: 'post',

**Comment by nhha1602** [comment]
Dear All,

After i tried to change the value of maxBodyLength, I continued to change it, but got error: "Too much data." as below logs.

Please advise this.

2020-04-14T04:33:50.183Z [^[[32minfo^[[39m] : POST at /data/convert/ user: qNTKoLTybm62HDgYy /imports/api/instances/instances.methods.js - rasa.getTrainingPayload with {"projectId":"bf","instance":{"_id":"mhHttGKJoLZvWJNj9","name":"Default Instance","host":"http://rasa:5005","projectId":"bf"},"language":""} url: http://rasa:5005/data/convert/
2020-04-14T04:34:00.663Z [^[[32minfo^[[39m] : POST at http://rasa:5005/data/convert/ succeeded user: qNTKoLTybm62HDgYy /imports/api/instances/instances.methods.js - rasa.getTrainingPayload with {"projectId":"bf","instance":{"_id":"mhHttGKJoLZvWJNj9","name":"Default Instance","host":"http://rasa:5005","projectId":"bf"},"language":""} 200 url: http://rasa:5005/data/convert/
2020-04-14T04:34:00.719Z [^[[32minfo^[[39m] : POST at /model/train user: qNTKoLTybm62HDgYy /imports/api/instances/instances.methods.js - rasa.train with {"projectId":"bf","instance":{"_id":"mhHttGKJoLZvWJNj9","name":"Default Instance","host":"http://rasa:5005","projectId":"bf"}} url: http://rasa:5005/model/train
2020-04-14T04:34:15.781Z [^[[31merror^[[39m] : POST at http://rasa:5005/model/train failed at response time user: qNTKoLTybm62HDgYy /imports/api/instances/instances.methods.js - rasa.train with {"projectId":"bf","instance":{"_id":"mhHttGKJoLZvWJNj9","name":"Default Instance","host":"http://rasa:5005","projectId":"bf"}} url: http://rasa:5005/model/train  data: "Too much data." error: Error: Request failed with status code 500
2020-04-14T04:34:15.831Z [^[[31merror^[[39m] : Training project bf - 26751.22 ms user: qNTKoLTybm62HDgYy /imports/api/instances/instances.methods.js - rasa.train with {"projectId":"bf","instance":{"_id":"mhHttGKJoLZvWJNj9","name":"Default Instance","host":"http://rasa:5005","projectId":"bf"}}    error: Error: Request failed with status code 500
{ Error: Request failed with status code 500
    at createError (/opt/bundle/bundle/programs/server/npm/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/bundle/bundle/programs/server/npm/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/bundle/bundle/programs/server/npm/node_modules/axios/lib/adapters/http.js:237:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
 => awaited here:
    at Function.Promise.await (/opt/bundle/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at Promise.asyncApply (imports/api/instances/instances.methods.js:287:39)
    at /opt/bundle/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
  config:

**Comment by znat** [comment]
@pheel that seems to be on the Rasa side, not graphql, right?

**Comment by alebeta90** [comment]
@znat it seems to be the same problem I had few weeks ago. And @pheel added a environment variable to increase the size of the Body limit on the expressjs side.

You could check #536

**Comment by nhha1602** [comment]
Hi,
I added GRAPHQL_REQUEST_SIZE_LIMIT: 1024mb to .botfront/botfront.yml but it is same issue.

I changed the values of maxBodyLength more that default below values it is OK

In /opt/bundle/bundle/programs/server/npm/node_modules/follow-redirects/index.js:

var exports = {
maxRedirects: 21,
maxBodyLength: 10 * 1024 * 1024,
};

But still got bellow errors:

2020-04-17T05:38:07.978Z [^[[31merror^[[39m] : POST at http://rasa:5005/model/train failed at response time user: o8uyzCDcJaiNhPZNq /imports/api/instances/instances.methods.js - rasa.train with {"projectId":"bf","instance":{"_id":"JXPoyetwTGgy2WN9y","name":"Default Instance","host":"http://rasa:5005","projectId":"bf"}} url: http://rasa:5005/model/train  data: "Too much data." error: Error: Request failed with status code 500
2020-04-17T05:38:08.030Z [^[[31merror^[[39m] : Training project bf - 304248.95 ms user: o8uyzCDcJaiNhPZNq /imports/api/instances/instances.methods.js - rasa.train with {"projectId":"bf","instance":{"_id":"JXPoyetwTGgy2WN9y","name":"Default Instance","host":"http://rasa:5005","projectId":"bf"}}    error: Error: Request failed with status code 500
{ Error: Request failed with status code 500
    at createError (/opt/bundle/bundle/programs/server/npm/node_modules/axios/lib/core/createError.js:16:15)


And

2020-04-17T06:14:32.994Z [^[[31merror^[[39m] : POST at http://rasa:5005/model/train failed at response time user: o8uyzCDcJaiNhPZNq /imports/api/instances/instances.methods.js - rasa.train with {"projectId":"bf","instance":{"_id":"JXPoyetwTGgy2WN9y","name":"Default Instance","host":"http://rasa:5005","projectId":"bf"}} url: http://rasa:5005/model/train  data: "Too much data." error: Error: timeout of 1800000ms exceeded
2020-04-17T06:14:33.046Z [^[[31merror^[[39m] : Training project bf - 1811423.03 ms user: o8uyzCDcJaiNhPZNq /imports/api/instances/instances.methods.js - rasa.train with {"projectId":"bf","instance":{"_id":"JXPoyetwTGgy2WN9y","name":"Default Instance","host":"http://rasa:5005","projectId":"bf"}}    error: Error: timeout of 1800000ms exceeded
{ Error: timeout of 1800000ms exceeded
    at createError (/opt/bundle/bundle/programs/server/npm/node_modules/axios/lib/core/createError.js:16:15)
    at Timeout.handleRequestTimeout (/opt/bundle/bundle/programs/server/npm/node_modules/axios/lib/adapters/http.js:252:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by alebeta90** [comment]
Hi @nhha1602 

I see in the error message `Error: timeout of 1800000ms exceeded`

@pheel maybe the training is taking longer than the timeout set by the nodejs app at the moment of the request?

all the best

**Comment by nhha1602** [comment]
Thank you for your response,

btw, i did not find instances.methods.js file on botfront-app docker.

Please advise this.
