### ISSUE TITLE
Error: ENOENT: no such file or directory, open botfront.yml

### ISSUE THREAD

**Issue by gerasimos** [botfront/botfront#570]
Hello,

I am on OSX, I have installed node using nvm, and I am getting the following error when trying to run `botfront`:

```
21:40 $ botfront 
Error: ENOENT: no such file or directory, open '/Users/g296/.botfront/botfront.yml'
    at Object.openSync (fs.js:462:3)
    at Proxy.readFileSync (fs.js:364:35)
    at getProjectConfig (/Users/g296/.nvm/versions/node/v13.13.0/lib/node_modules/botfront/src/utils.js:240:29)
    at getProjectVersion (/Users/g296/.nvm/versions/node/v13.13.0/lib/node_modules/botfront/src/utils.js:93:12)
    at isMinorUpdate (/Users/g296/.nvm/versions/node/v13.13.0/lib/node_modules/botfront/src/utils.js:116:28)
    at general (/Users/g296/.nvm/versions/node/v13.13.0/lib/node_modules/botfront/src/cli.js:175:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/g296/.botfront/botfront.yml'
}
```

The file mentioned does not exist.

Thank you,
Gerasimos

**Comment by znat** [comment]
Hi, it's a known issue. All commands do work though. See `botfront --help`
