### ISSUE TITLE
Development Mode : Training failed: "timeout [399]"

### ISSUE THREAD

**Issue by engahmed1190** [botfront/botfront#580]
**Describe the bug**
botfront-rasa failed to get configuration from graphql at development mode.  

Botfront Version : 0.22.2
Botfront Rasa : v1.9.0-bf.5

**Rasa Error** 

```
2020-04-26 14:26:48 DEBUG    rasa.utils.botfront  - Trying to fetch config from server (retry #92)
2020-04-26 14:26:48 DEBUG    sgqlc.endpoint.http  - Query:

query($projectId: String!) {
        getConfig(projectId: $projectId) {
        credentials
        endpoints
    }
}
```

**Botfront Error**
```
I20200426-14:40:08.997(0)? 2020-04-26T14:40:08.978Z [error] : Building training payload failed - 23.62 ms user: SLA8LJYd5WLPrZcf7 /imports/api/instances/instances.methods.js - rasa.getTrainingPayload with {"projectId":"bf","instance":{"_id":"maAsDwTK9o6oNyYRo","name":"Default Instance","host":"http://rasa:5005","projectId":"bf"},"language":""}    
I20200426-14:40:08.999(0)? { Error: getaddrinfo EAI_AGAIN rasa:5005
I20200426-14:40:09.007(0)?     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
I20200426-14:40:09.009(0)?  => awaited here:
I20200426-14:40:09.009(0)?     at Function.Promise.await (/.meteor/packages/promise/.0.11.2.1bomg6e.mbyx++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20200426-14:40:09.010(0)?     at Promise.asyncApply (imports/api/instances/instances.methods.js:231:27)
I20200426-14:40:09.011(0)?     at .meteor/packages/promise/.0.11.2.1bomg6e.mbyx++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20200426-14:40:09.011(0)?   errno: 'EAI_AGAIN',
I20200426-14:40:09.012(0)?   code: 'EAI_AGAIN',
I20200426-14:40:09.013(0)?   syscall: 'getaddrinfo',
I20200426-14:40:09.015(0)?   hostname: 'rasa',
I20200426-14:40:09.016(0)?   host: 'rasa',
I20200426-14:40:09.016(0)?   port: '5005',
I20200426-14:40:09.016(0)?   config:
I20200426-14:27:32.379(0)?      headers: 
I20200426-14:27:32.382(0)?       { Accept: 'application/json, text/plain, */*',
I20200426-14:27:32.382(0)?         'Content-Type': 'application/json;charset=utf-8',
I20200426-14:27:32.383(0)?         'User-Agent': 'axios/0.19.0',
I20200426-14:27:32.384(0)?         'Content-Length': 5767 },
I20200426-14:27:32.386(0)?      baseURL: 'http://rasa:5005',
I20200426-14:27:32.387(0)?      transformRequest: [ [Function: transformRequest] ],
I20200426-14:27:32.387(0)?      transformResponse: [ [Function: transformResponse] ],
I20200426-14:27:32.387(0)?      timeout: 180000,
I20200426-14:27:32.389(0)?      adapter: [Function: httpAdapter],
I20200426-14:27:32.391(0)?      xsrfCookieName: 'XSRF-TOKEN',
I20200426-14:27:32.392(0)?      xsrfHeaderName: 'X-XSRF-TOKEN',
I20200426-14:27:32.392(0)?      maxContentLength: -1,
I20200426-14:27:32.393(0)?      validateStatus: [Function: validateStatus] },
I20200426-14:27:32.394(0)?   request: 
I20200426-14:27:32.397(0)?    Writable {
I20200426-14:27:32.397(0)?      _writableState: 
I20200426-14:27:32.398(0)?       WritableState {
I20200426-14:27:32.398(0)?         objectMode: false,
I20200426-14:27:32.399(0)?         highWaterMark: 16384,
I20200426-14:27:32.399(0)?         finalCalled: false,
I20200426-14:27:32.401(0)?         needDrain: false,
I20200426-14:27:32.401(0)?         ending: false,
I20200426-14:27:32.402(0)?         ended: false,
I20200426-14:27:32.403(0)?         finished: false,
I20200426-14:27:32.404(0)?         destroyed: false,
I20200426-14:27:32.404(0)?         decodeStrings: true,
I20200426-14:27:32.405(0)?         defaultEncoding: 'utf8',
I20200426-14:27:32.407(0)?         length: 0,
I20200426-14:27:32.408(0)?         writing: false,
I20200426-14:27:32.412(0)?         corked: 0,
I20200426-14:27:32.412(0)?         sync: true,
I20200426-14:27:32.413(0)?         bufferProcessing: false,
I20200426-14:27:32.413(0)?         onwrite: [Function: bound onwrite],
I20200426-14:27:32.414(0)?         writecb: null,
I20200426-14:27:32.414(0)?         writelen: 0,
I20200426-14:27:32.415(0)?         bufferedRequest: null,
I20200426-14:27:32.416(0)?         lastBufferedRequest: null,
I20200426-14:27:32.417(0)?         pendingcb: 0,
I20200426-14:27:32.417(0)?         prefinished: false,
I20200426-14:27:32.418(0)?         errorEmitted: false,
I20200426-14:27:32.419(0)?         bufferedRequestCount: 0,
I20200426-14:27:32.419(0)?         corkedRequestsFree: [Object] },
I20200426-14:27:32.420(0)?      writable: true,
I20200426-14:27:32.420(0)?      domain: null,
I20200426-14:27:32.421(0)?      _events: 
I20200426-14:27:32.421(0)?       { response: [Function: handleResponse],
I20200426-14:27:32.422(0)?         error: [Function: handleRequestError] },
I20200426-14:27:32.422(0)?      _eventsCount: 2,
I20200426-14:27:32.423(0)?      _maxListeners: undefined,
I20200426-14:27:32.423(0)?      _options: 
I20200426-14:27:32.438(0)?       { protocol: 'http:',
I20200426-14:27:32.439(0)?         maxRedirects: 21,
I20200426-14:27:32.439(0)?         maxBodyLength: 10485760,
I20200426-14:27:32.440(0)?         path: '/data/convert/',
I20200426-14:27:32.440(0)?         method: 'POST',
I20200426-14:27:32.440(0)?         headers: [Object],
I20200426-14:27:32.441(0)?         agent: undefined,
I20200426-14:27:32.441(0)?         auth: undefined,
I20200426-14:27:32.442(0)?         hostname: 'rasa',
I20200426-14:27:32.442(0)?         port: '5005',
I20200426-14:27:32.443(0)?         nativeProtocols: [Object],
I20200426-14:27:32.443(0)?         pathname: '/data/convert/' },
I20200426-14:27:32.444(0)?      _redirectCount: 0,
I20200426-14:27:32.444(0)?      _redirects: [],
I20200426-14:27:32.445(0)?      _requestBodyLength: 5767,
I20200426-14:27:32.445(0)?      _requestBodyBuffers: [ [Object] ],
I20200426-14:27:32.445(0)?      _onNativeResponse: [Function],
I20200426-14:27:32.446(0)?      _currentRequest: 
I20200426-14:27:32.446(0)?       ClientRequest {
I20200426-14:27:32.447(0)?         domain: null,
I20200426-14:27:32.447(0)?         _events: [Object],
I20200426-14:27:32.448(0)?         _eventsCount: 6,
I20200426-14:27:32.448(0)?         _maxListeners: undefined,
I20200426-14:27:32.449(0)?         output: [],
I20200426-14:27:32.449(0)?         outputEncodings: [],
I20200426-14:27:32.450(0)?         outputCallbacks: [],
I20200426-14:27:32.450(0)?         outputSize: 0,
I20200426-14:27:32.451(0)?         writable: true,
I20200426-14:27:32.451(0)?         _last: true,
I20200426-14:27:32.452(0)?         upgrading: false,
I20200426-14:27:32.452(0)?         chunkedEncoding: false,
I20200426-14:27:32.452(0)?         shouldKeepAlive: false,
I20200426-14:27:32.453(0)?         useChunkedEncodingByDefault: true,
I20200426-14:27:32.454(0)?         sendDate: false,
I20200426-14:27:32.454(0)?         _removedConnection: false,
I20200426-14:27:32.454(0)?         _removedContLen: false,
I20200426-14:27:32.455(0)?         _removedTE: false,
I20200426-14:27:32.455(0)?         _contentLength: null,
I20200426-14:27:32.456(0)?         _hasBody: true,
I20200426-14:27:32.456(0)?         _trailer: '',
I20200426-14:27:32.456(0)?         finished: false,
I20200426-14:27:32.457(0)?         _headerSent: true,
I20200426-14:27:32.457(0)?         socket: [Object],
I20200426-14:27:32.458(0)?         connection: [Object],
I20200426-14:27:32.458(0)?         _header: 'POST /data/convert/ HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json;charset=utf-8\r\nUser-Agent: axios/0.19.0\r\nContent-Length: 5767\r\nHost: rasa:5005\r\nConnection: close\r\n\r\n',
I20200426-14:27:32.459(0)?         _onPendingData: [Function: noopPendingOutput],
I20200426-14:27:32.459(0)?         agent: [Object],
I20200426-14:27:32.460(0)?         socketPath: undefined,
I20200426-14:27:32.460(0)?         timeout: undefined,
I20200426-14:27:32.461(0)?         method: 'POST',
I20200426-14:27:32.467(0)?         path: '/data/convert/',
I20200426-14:27:32.467(0)?         _ended: false,
I20200426-14:27:32.468(0)?         res: null,
I20200426-14:27:32.468(0)?         aborted: undefined,
I20200426-14:27:32.468(0)?         timeoutCb: null,
I20200426-14:27:32.469(0)?         upgradeOrConnect: false,
I20200426-14:27:32.469(0)?         parser: null,
I20200426-14:27:32.470(0)?         maxHeadersCount: null,
I20200426-14:27:32.470(0)?         _redirectable: [Circular],
I20200426-14:27:32.471(0)?         [Symbol(outHeadersKey)]: [Object] },
I20200426-14:27:32.471(0)?      _currentUrl: 'http://rasa:5005/data/convert/' },
I20200426-14:27:32.472(0)?   response: undefined,
I20200426-14:27:32.472(0)?   isAxiosError: true,
I20200426-14:27:32.473(0)?   toJSON: [Function] }
I20200426-14:27:32.475(0)? 2020-04-26T14:27:32.368Z [error] : Training project bf - 68.29 ms user: SLA8LJYd5WLPrZcf7 /imports/api/instances/instances.methods.js - rasa.train with {"projectId":"bf","instance":{"_id":"maAsDwTK9o6oNyYRo","name":"Default Instance","host":"http://rasa:5005","projectId":"bf"}}    error: Error: timeout [399]
```

botfront running on 3000
botfront api running on 8080

botfront-rasa failed to capture the configuration

**Comment by engahmed1190** [comment]
I have found it returns **Too much data** although I added 2 intents only.  


```
20200427-09:49:07.329(0)? 2020-04-27T09:49:07.328Z [error] : POST at http://rasa:5005/data/convert/ failed at response time user: SLA8LJYd5WLPrZcf7 /imports/api/instances/instances.methods.js - rasa.getTrainingPayload with {"projectId":"bf","instance":{"_id":"maAsDwTK9o6oNyYRo","name":"Default Instance","host":"http://rasa:5005","projectId":"bf"},"language":""} url: http://rasa:5005/data/convert/  data: "Too much data." error: Error: getaddrinfo EAI_AGAIN rasa:5005
I20200427-09:49:07.333(0)? 2020-04-27T09:49:07.332Z [error] : Building training payload failed - 73.07 ms user: SLA8LJYd5WLPrZcf7 /imports/api/instances/instances.methods.js - rasa.getTrainingPayload with {"projectId":"bf","instance":{"_id":"maAsDwTK9o6oNyYRo","name":"Default Instance","host":"http://rasa:5005","projectId":"bf"},"language":""}
```

**Comment by pheel** [comment]
The two errors show Botfront and Rasa are not communicating properly: Rasa is not able to fetch its initial config from Botfront and boot, and Botfront is not able to access Rasa's `/convert` endpoint. 

You say you're using Botfront in "development mode", which must mean you're running Meteor outside a container. We used to host a guide at https://docs.botfront.io/developers-guide/ (@znat where did it go?) but basically you need to change your endpoints and instance to point to addresses resolvable to and from your Docker host.

On Mac, we recommend substituting `host.docker.internal:3000` for `botfront:3000`, `host.docker.internal:5005` for `rasa:5005` and `host.docker.internal:8080` for `botfront-api:8080`.

> I have found it returns **Too much data** although I added 2 intents only.
> 

The "too much data" part is unfortunate wording for saying response was too long to print on a log line. We'll change this.

**Comment by znat** [comment]
The guide to run Botfront in development mode is here: https://botfront.io/docs/contributing

**Comment by engahmed1190** [comment]
Thanks, @pheel and @znat . 
Can you please add more loggers at the [graphql.py](https://github.com/botfront/rasa-addons/blob/master/rasa_addons/core/channels/graphql.py)

Seems to be very hard to understand where it fails and Thanks in advance

**Comment by pheel** [comment]
> Can you please add more loggers at the [graphql.py](https://github.com/botfront/rasa-addons/blob/master/rasa_addons/core/channels/graphql.py)

You linked to rasa_addons.core.channels.graphql, but it's rasa(-for-botfront).utils.botfront. We could add to "Trying to fetch config from server" to clarify which host was unreachable, and give a short help message.
