### ISSUE TITLE
rasa.core.lock_store  - Failed to acquire lock for conversation ID

### ISSUE THREAD

**Issue by alebeta90** [botfront/botfront#589]
**Describe the bug**
Bot does not deliver messages and is in loop always repeating it self

Rasa version: rasa-for-botfront:v1.9.0-bf.7
Channel: Facebook Messenger

This are the errors we can see in the logs

```
2020-05-01 17:19:24 DEBUG    rasa.core.lock_store  - Failed to acquire lock for conversation ID '2969844866'. Retrying...
2020-05-01 17:19:24 DEBUG    rasa.core.lock_store  - Failed to acquire lock for conversation ID '2824721860'. Retrying...
2020-05-01 17:19:24 DEBUG    rasa.core.lock_store  - Failed to acquire lock for conversation ID '2982392281'. Retrying...
2020-05-01 17:19:24 DEBUG    rasa.core.lock_store  - Failed to acquire lock for conversation ID '3279745035'. Retrying...
2020-05-01 17:19:24 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_countr_metrics'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-05-01 17:19:24 DEBUG    rasa.core.processor  - 
Traceback (most recent call last):
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/processor.py", line 627, in _run_action
    events = await action.run(output_channel, nlg, tracker, self.domain)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/actions/action.py", line 550, in run
    json=json_body, method="post", timeout=DEFAULT_REQUEST_TIMEOUT
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/opt/venv/lib/python3.6/site-packages/rasa/utils/endpoints.py", line 146, in request
    **kwargs,
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/opt/venv/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/opt/venv/lib/python3.6/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/opt/venv/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/opt/venv/lib/python3.6/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
concurrent.futures._base.CancelledError
```

if more information is needed please let me know

all the best

**Comment by GuillaumeTech** [comment]
Hi @alebeta90,

Can you provide your configuration of endpoints ? Are you running botfront locally or is it deployed somewhere ?

**Comment by rtogari7** [comment]
Hi,

Same issue i am also facing. 

Rasa version =1.7.2
Hosted on the cloud foundry

Thanks,
Ramesh

**Comment by rtogari7** [comment]
Logs for the same

WEB/0] [ERR] 2020-07-01 04:10:28 DEBUG rasa.core.actions.action - Calling action endpoint to run action 'action_
2020-07-01T09:40:28.491+05:30 [APP/PROC/WEB/0] [ERR] 2020-07-01 04:10:28 DEBUG rasa.core.lock_store - Failed to acquire lock for conversation ID ''. Retrying...
2020-07-01T09:40:28.635+05:30 [APP/PROC/WEB/0] [ERR] 2020-07-01 04:10:28 DEBUG rasa.core.lock_store - Failed to acquire lock for conversation ID ''. Retrying...
2020-07-01T09:40:28.695+05:30 [APP/PROC/WEB/0] [ERR] 2020-07-01 04:10:28 DEBUG rasa.core.lock_store - Failed to acquire lock for conversation ID ''. Retrying...
2020-07-01T09:40:29.498+05:30 [APP/PROC/WEB/0] [ERR] 2020-07-01 04:10:29 DEBUG rasa.core.lock_store - Failed to acquire lock for conversation ID ''. Retrying...
2020-07-01T09:40:29.516+05:30 [APP/PROC/WEB/0] [ERR] 2020-07-01 04:10:29 DEBUG rasa.core.lock_store - Failed to acquire lock for conversation ID ''. Retrying...

**Comment by GuillaumeTech** [comment]
Hi !
Can you show me what you have in your endpoints ? also try updating rasa and botfront, it might resolve the issue since the 1.7.2 is a bit outated

**Comment by rtogari7** [comment]
Hi 
my end point :
https://XXXX_issal_XXX_esactions.ausmpc01.pcf.XXX.com/webhook" 

The bot is hosted on the cloud foundry, sorry i did not get botfront ...

**Comment by JiteshGaikwad** [comment]
hey @rtogari7 @alebeta90 did you found the solution for the above issue?

**Comment by JiteshGaikwad** [comment]
@alebeta90 I am using REST channel and I have the latest Rasa version 1.10.8 and I am facing the same issue, can you help?

**Comment by robynbitner** [comment]
Are there any updates on this? I am also having the same problem.

**Comment by rtogari7** [comment]
Make sure that DB connection happened properly, in my case there were credentials mismatch. Now i got resolved with correct DB credentials in the end points of bot
