### ISSUE TITLE
Cannot train after import

### ISSUE THREAD

**Issue by marcopeix** [botfront/botfront#592]
**Describe the bug**
After importing a Botfront project, the model cannot be trained

**To Reproduce**
1. Import a Botfront project (JSON file)
2. Navigate to NLU and click on "Train everything"
3. See error: "Training failed: timeout[399]"

**Expected behavior**
The model trains

**Screenshots**
![image](https://user-images.githubusercontent.com/19268689/81313330-c0d49a80-9055-11ea-9c91-aff127b9cd72.png)

**Desktop (please complete the following information):**
 - OS: CentOS
 - Browser: Chrome
 - Botfront: v0.23

**Additional context**
Here is the full error log:
```
botfront-app    |      headers: 
botfront-app    |       { Accept: 'application/json, text/plain, */*',
botfront-app    |         'Content-Type': 'application/json;charset=utf-8',
botfront-app    |         'User-Agent': 'axios/0.19.0',
botfront-app    |         'Content-Length': 154132 },
botfront-app    |      baseURL: 'http://svc-vsd-faq-chatbot.5648-nonproduction-development.svc.cluster.local',
botfront-app    |      transformRequest: [ [Function: transformRequest] ],
botfront-app    |      transformResponse: [ [Function: transformResponse] ],
botfront-app    |      timeout: 180000,
botfront-app    |      adapter: [Function: httpAdapter],
botfront-app    |      xsrfCookieName: 'XSRF-TOKEN',
botfront-app    |      xsrfHeaderName: 'X-XSRF-TOKEN',
botfront-app    |      maxContentLength: -1,
botfront-app    |      validateStatus: [Function: validateStatus] },
botfront-app    |   request: 
botfront-app    |    Writable {
botfront-app    |      _writableState: 
botfront-app    |       WritableState {
botfront-app    |         objectMode: false,
botfront-app    |         highWaterMark: 16384,
botfront-app    |         finalCalled: false,
botfront-app    |         needDrain: false,
botfront-app    |         ending: false,
botfront-app    |         ended: false,
botfront-app    |         finished: false,
botfront-app    |         destroyed: false,
botfront-app    |         decodeStrings: true,
botfront-app    |         defaultEncoding: 'utf8',
botfront-app    |         length: 0,
botfront-app    |         writing: false,
botfront-app    |         corked: 0,
botfront-app    |         sync: true,
botfront-app    |         bufferProcessing: false,
botfront-app    |         onwrite: [Function: bound onwrite],
botfront-app    |         writecb: null,
botfront-app    |         writelen: 0,
botfront-app    |         bufferedRequest: null,
botfront-app    |         lastBufferedRequest: null,
botfront-app    |         pendingcb: 0,
botfront-app    |         prefinished: false,
botfront-app    |         errorEmitted: false,
botfront-app    |         bufferedRequestCount: 0,
botfront-app    |         corkedRequestsFree: [Object] },
botfront-app    |      writable: true,
botfront-app    |      domain: null,
botfront-app    |      _events: 
botfront-app    |       { response: [Function: handleResponse],
botfront-app    |         error: [Function: handleRequestError] },
botfront-app    |      _eventsCount: 2,
botfront-app    |      _maxListeners: undefined,
botfront-app    |      _options: 
botfront-app    |       { protocol: 'http:',
botfront-app    |         maxRedirects: 21,
botfront-app    |         maxBodyLength: 10485760,
botfront-app    |         path: '/data/convert/',
botfront-app    |         method: 'POST',
botfront-app    |         headers: [Object],
botfront-app    |         agent: undefined,
botfront-app    |         auth: undefined,
botfront-app    |         hostname: 'svc-vsd-faq-chatbot.5648-nonproduction-development.svc.cluster.local',
botfront-app    |         port: null,
botfront-app    |         nativeProtocols: [Object],
botfront-app    |         pathname: '/data/convert/' },
botfront-app    |      _redirectCount: 0,
botfront-app    |      _redirects: [],
botfront-app    |      _requestBodyLength: 154132,
botfront-app    |      _requestBodyBuffers: [ [Object] ],
botfront-app    |      _onNativeResponse: [Function],
botfront-app    |      _currentRequest: 
botfront-app    |       ClientRequest {
botfront-app    |         domain: null,
botfront-app    |         _events: [Object],
botfront-app    |         _eventsCount: 6,
botfront-app    |         _maxListeners: undefined,
botfront-app    |         output: [],
botfront-app    |         outputEncodings: [],
botfront-app    |         outputCallbacks: [],
botfront-app    |         outputSize: 0,
botfront-app    |         writable: true,
botfront-app    |         _last: true,
botfront-app    |         upgrading: false,
botfront-app    |         chunkedEncoding: false,
botfront-app    |         shouldKeepAlive: false,
botfront-app    |         useChunkedEncodingByDefault: true,
botfront-app    |         sendDate: false,
botfront-app    |         _removedConnection: false,
botfront-app    |         _removedContLen: false,
botfront-app    |         _removedTE: false,
botfront-app    |         _contentLength: null,
botfront-app    |         _hasBody: true,
botfront-app    |         _trailer: '',
botfront-app    |         finished: false,
botfront-app    |         _headerSent: true,
botfront-app    |         socket: [Object],
botfront-app    |         connection: [Object],
botfront-app    |         _header: 'POST /data/convert/ HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json;charset=utf-8\r\nUser-Agent: axios/0.19.0\r\nContent-Length: 154132\r\nHost: svc-vsd-faq-chatbot.5648-nonproduction-development.svc.cluster.local\r\nConnection: close\r\n\r\n',
botfront-app    |         _onPendingData: [Function: noopPendingOutput],
botfront-app    |         agent: [Object],
botfront-app    |         socketPath: undefined,
botfront-app    |         timeout: undefined,
botfront-app    |         method: 'POST',
botfront-app    |         path: '/data/convert/',
botfront-app    |         _ended: false,
botfront-app    |         res: null,
botfront-app    |         aborted: undefined,
botfront-app    |         timeoutCb: null,
botfront-app    |         upgradeOrConnect: false,
botfront-app    |         parser: null,
botfront-app    |         maxHeadersCount: null,
botfront-app    |         _redirectable: [Circular],
botfront-app    |         [Symbol(outHeadersKey)]: [Object] },
botfront-app    |      _currentUrl: 'http://svc-vsd-faq-chatbot.5648-nonproduction-development.svc.cluster.local/data/convert/' },
botfront-app    |   response: undefined,
botfront-app    |   isAxiosError: true,
botfront-app    |   toJSON: [Function] }
botfront-app    | 2020-05-07T15:19:23.357Z [error] : Training project bf - 76.97 ms user: pGzkSZGu6xmXndRHz /imports/api/instances/instances.methods.js - rasa.train with {"projectId":"bf","instance":{"_id":"fa055dd6-5f68-4383-b207-959b92a9e7d1","name":"Default","host":"http://svc-vsd-faq-chatbot.5648-nonproduction-development.svc.cluster.local","projectId":"bf"}}    error: Error: timeout [399]
botfront-app    | { Error: timeout [399]
botfront-app    |     at getAxiosError (imports/lib/utils.js:73:17)
botfront-app    |     at Promise.asyncApply (imports/api/instances/instances.methods.js:258:23)
botfront-app    |     at /opt/bundle/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
botfront-app    |  => awaited here:
botfront-app    |     at Promise.await (/opt/bundle/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
botfront-app    |     at Server.apply (packages/ddp-server/livedata_server.js:1638:14)
botfront-app    |     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
botfront-app    |     at Promise.asyncApply (imports/api/instances/instances.methods.js:280:46)
botfront-app    |     at /opt/bundle/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
botfront-app    |   isClientSafe: true,
botfront-app    |   error: '399',
botfront-app    |   reason: 'timeout',
botfront-app    |   details: undefined,
botfront-app    |   message: 'timeout [399]',
botfront-app    |   errorType: 'Meteor.Error' }
```

**Comment by marcopeix** [comment]
Solution:
- Navigate to Settings -> Instance
- Make sure the host is set to http://{IPAddress}:5005
