### ISSUE TITLE
Form Policy Error 

### ISSUE THREAD

**Issue by engahmed1190** [botfront/botfront#650]
**Describe the bug**
rasa-for-botfront unable to run the Form Action Policy 

Story Example 

```
* inform_checkBalance
- action_slot_reset
- utter_check_help
- check_balance_form
- form {"name":"check_balance_form"}
- form {"name": null}
- slot{"name": "david"}
- slot{"age":"33"}
- slot{"account_id": "0123654789654123"}
- slot{"email": "test.test@test.com"}
- action_check_balance
- action_send_email_checkbalance
- utter_creatSubmit
- utter_ask_for_anotherProcess
```

Error : 

```
020-06-28 19:36:03 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<AsyncServer._handle_event_internal() done, defined at /opt/venv/lib/python3.6/site-packages/socketio/asyncio_server.py:469> exception=TypeError("'NoneType' object is not iterable",) created at /opt/venv/lib/python3.6/site-packages/engineio/asyncio_server.py:322>
source_traceback: Object created at (most recent call last):
  File "/opt/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.6/site-packages/rasa/__main__.py", line 91, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/opt/venv/lib/python3.6/site-packages/rasa/cli/run.py", line 87, in run
    rasa.run(**vars(args))
  File "/opt/venv/lib/python3.6/site-packages/rasa/run.py", line 56, in run
    **kwargs,
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/run.py", line 217, in serve_application
    endpoints.lock_store if endpoints else None
  File "/opt/venv/lib/python3.6/site-packages/sanic/app.py", line 1167, in run
    serve(**server_settings)
  File "/opt/venv/lib/python3.6/site-packages/sanic/server.py", line 920, in serve
    loop.run_forever()
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 126, in send
    return self.gen.send(value)
  File "/opt/venv/lib/python3.6/site-packages/spf/framework.py", line 554, in _handle_request
    stream_callback)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/opt/venv/lib/python3.6/site-packages/sanic/app.py", line 976, in handle_request
    response = await response
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/opt/venv/lib/python3.6/site-packages/engineio/asyncio_server.py", line 251, in handle_request
    packets = await socket.handle_get_request(environ)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/opt/venv/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 93, in handle_get_request
    return await getattr(self, '_upgrade_' + transport)(environ)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/opt/venv/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 136, in _upgrade_websocket
    return await ws(environ)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/opt/venv/lib/python3.6/site-packages/engineio/async_drivers/sanic.py", line 122, in __call__
    await self.handler(self)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/opt/venv/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 228, in _websocket_handler
    await self.receive(pkt)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/opt/venv/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 47, in receive
    run_async=self.server.async_handlers)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/opt/venv/lib/python3.6/site-packages/engineio/asyncio_server.py", line 420, in _trigger_event
    ret = await self.handlers[event](*args)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/opt/venv/lib/python3.6/site-packages/socketio/asyncio_server.py", line 537, in _handle_eio_message
    await self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/opt/venv/lib/python3.6/site-packages/socketio/asyncio_server.py", line 465, in _handle_event
    data, namespace, id)
  File "/opt/venv/lib/python3.6/site-packages/socketio/asyncio_server.py", line 368, in start_background_task
    return self.eio.start_background_task(target, *args, **kwargs)
  File "/opt/venv/lib/python3.6/site-packages/engineio/asyncio_server.py", line 322, in start_background_task
    return asyncio.ensure_future(target(*args, **kwargs))
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 126, in send
    return self.gen.send(value)
  File "/opt/venv/lib/python3.6/site-packages/socketio/asyncio_server.py", line 470, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/opt/venv/lib/python3.6/site-packages/socketio/asyncio_server.py", line 498, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/opt/venv/lib/python3.6/site-packages/rasa_addons/core/channels/webchat.py", line 238, in handle_message
    await on_new_message(message)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 83, in handler
    await app.agent.handle_message(*args, **kwargs)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/agent.py", line 505, in handle_message
    return await processor.handle_message(message)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/processor.py", line 108, in handle_message
    await self._predict_and_execute_next_action(message.output_channel, tracker)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/processor.py", line 564, in _predict_and_execute_next_action
    action, policy, confidence = self.predict_next_action(tracker)
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/processor.py", line 306, in predict_next_action
    tracker.slots.get("bf_forms", Slot("bf_forms")).initial_value, # bf
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/domain.py", line 541, in action_for_index
    return self.action_for_name(self.action_names[index], action_endpoint, bf_form_slot) # bf
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/domain.py", line 523, in action_for_name
    action_name, action_endpoint, self.user_actions_and_forms, bf_form_slot # bf
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/actions/action.py", line 117, in action_from_name
    elif name.endswith("_form") and any(slot.get("name") == name for slot in bf_form_slot): # bf
TypeError: 'NoneType' object is not iterable

```

**Comment by znat** [comment]
On which version are you (botfront and rasa)

**Comment by engahmed1190** [comment]
Versions 
    botfront: botfront:v0.25.0-rc.1
    rasa: rasa-for-botfront:v1.10.1-bf.1

**Comment by pheel** [comment]
Hi @engahmed1190,
Thanks as always for your bug reports.
This is fixed in https://github.com/botfront/rasa-for-botfront/releases/tag/v1.10.3-bf.1.
