### ISSUE TITLE
Botfront resets automatically and the project gets deleted

### ISSUE THREAD

**Issue by satishp962** [botfront/botfront#776]
So, I have the Botfront setup on my Linux cloud instance hosted on OVHCloud.

It is set up correctly and works fine. But after some time my project gets deleted and I am also logged out automatically in the console.

I have not modified anything in the docker-compose.yml file.

I am clueless what's happening with my system, please help.

**Comment by znat** [comment]
This is probably because the volume for MongoDB has not been defined.
Check out lines 85 and 95 in https://github.com/botfront/botfront/blob/master/cli/project-template/.botfront/docker-compose-template.yml

**Comment by satishp962** [comment]
It is defined. I did not make any change in the docker-compose file.

![image](https://user-images.githubusercontent.com/8225877/95558845-7efcb580-0a34-11eb-8dc4-12e7e24b6d8c.png)

**Comment by oguzhankarahan** [comment]
Yes, I have a similar error on the server.

**Comment by znat** [comment]
There is no way for Botfront to wipe all data from the database. The only possible cause is that the persisted data is not available anymore. And the most likely reason would be that something when wrong with the volume. If the volume is not created, the data will remain in the mongo container. And when shutting botfront down, the container will be recreated and the data will be lost.
I would suggest you verify that when Botfront is up you can find the `botfront-db` folder that that it contains a whole lot of database files.

**Comment by oguzhankarahan** [comment]
I understood the problem. This problem was caused by a cyber attack. Someone dumped the mongodb data (bf) of the project on the server. And deleted. Next, a database named "READ_ME_TO_RECOVER_YOUR_DATA" was created. They created a collection called README into this database and requested 0.04 bitcoins.

So, they connected to the server, deleted the database and wanted to get money. I closed all ports on the server, there was no cyber attack again.

There have been many cyber attacks recently. Please be careful.

**Comment by satishp962** [comment]
> that it contains a whole lot of database files.

@znat  Yeah.. It's all there. I am still not sure what causes this to happen. Also, there are no cyber attacks on my server @oguzhankarahan.

**Comment by satishp962** [comment]
@znat Please help. I am still having this issue.

**Comment by yingkai1181** [comment]
I have the exact same issue, my setup got reset less than 24 hrs, nothing touched.. weird, plz help~

**Comment by satishp962** [comment]
Thanks @yingkai1181 for bringing this to light.

**Comment by yingkai1181** [comment]
@satishp962 

Hi, I'm on 0.27.2 for a while, and did not upgrade to 0.27.4, all good until last night, the site ask me to recreate a project, it happened before, I thought it was the upgrade issue before, so I did a clean 0.27.2 installation, but this time I did not touch anything, I have models folder on 777 (owner is root), the bofront-db folder on 755 (owner is polkitd), I think maybe it's the botfront-db folder permission, so I did a snapshot recover and changed botfront-db folder permission to 777, now I'm waiting to see when it will reset again:( , below is the botfront logs before snapshot recover, please advise~ ^^ :


2020-11-08 15:40:43 DEBUG rasaaddons.core.channels.webchat - User b2983fd4fc964ad68380ab11291435fc disconnected from socketIO endpoint.
botfront-rasa | 2020-11-08 15:40:44 DEBUG rasaaddons.core.channels.webchat - User 87a06c9ecb9b42abb445ad3457165e37 connected to socketIO endpoint.
botfront-rasa | 2020-11-08 15:40:44 DEBUG rasa_addons.core.channels.graphql - fetching endpoints and credentials at http://botfront:3000/graphql
botfront-rasa | 2020-11-08 15:40:44 ERROR sgqlc.endpoint.http - GraphQL query failed with 1 errors
botfront-rasa | 2020-11-08 15:40:44 ERROR rasa_addons.core.channels.graphql - Something went wrong fetching config at http://botfront:3000/graphql: Cannot destructure property 'endpoints' of 'endpointsFetched' as it is null.
botfront-rasa | 2020-11-08 15:40:44 ERROR asyncio - Task exception was never retrieved
botfront-rasa | future: <Task finished coro=<AsyncServer._handle_event_internal() done, defined at /opt/venv/lib/python3.7/site-packages/socketio/asyncio_server.py:469> exception=TypeError("'NoneType' object is not subscriptable") created at /opt/venv/lib/python3.7/site-packages/engineio/asyncio_server.py:322>
botfront-rasa | source_traceback: Object created at (most recent call last):
botfront-rasa | File "/opt/venv/bin/rasa", line 8, in <module>
botfront-rasa | sys.exit(main())
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/rasa/\_main_.py", line 92, in main
botfront-rasa | cmdline_arguments.func(cmdline_arguments)
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/rasa/cli/run.py", line 87, in run
botfront-rasa | rasa.run(vars(args))
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/rasa/run.py", line 56, in run
botfront-rasa | kwargs,
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/rasa/core/run.py", line 216, in serve_application
botfront-rasa | endpoints.lock_store if endpoints else None
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/sanic/app.py", line 1167, in run
botfront-rasa | serve(server_settings)
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/sanic/server.py", line 920, in serve
botfront-rasa | loop.run_forever()
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/spf/framework.py", line 554, in _handle_request
botfront-rasa | stream_callback)
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/sanic/app.py", line 976, in handle_request
botfront-rasa | response = await response
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/engineio/asyncio_server.py", line 270, in handle_request
botfront-rasa | await socket.handle_post_request(environ)
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/engineio/asyncio_socket.py", line 115, in handle_post_request
botfront-rasa | await self.receive(pkt)
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/engineio/asyncio_socket.py", line 47, in receive
botfront-rasa | run_async=self.server.async_handlers)
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/engineio/asyncio_server.py", line 420, in _trigger_event
botfront-rasa | ret = await self.handlersevent
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/socketio/asyncio_server.py", line 537, in _handle_eio_message
botfront-rasa | await self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/socketio/asyncio_server.py", line 465, in _handle_event
botfront-rasa | data, namespace, id)
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/socketio/asyncio_server.py", line 368, in start_background_task
botfront-rasa | return self.eio.start_background_task(target, *args, kwargs)
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/engineio/asyncio_server.py", line 322, in start_background_task
botfront-rasa | return asyncio.ensure_future(target(_args, **kwargs))
botfront-rasa | Traceback (most recent call last):
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/socketio/asyncio_server.py", line 470, in _handle_event_internal
botfront-rasa | r = await server._trigger_event(data[0], namespace, sid, _data[1:])
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/socketio/asyncio_server.py", line 498, in _trigger_event
botfront-rasa | ret = await self.handlers[namespace]event
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/rasa_addons/core/channels/webchat.py", line 220, in session_request
botfront-rasa | os.environ.get("BF_URL"), os.environ.get("BF_PROJECT_ID")
botfront-rasa | File "/opt/venv/lib/python3.7/site-packages/rasa_addons/core/channels/graphql.py", line 57, in get_config_via_graphql
botfront-rasa | return data["getConfig"]
botfront-rasa | TypeError: 'NoneType' object is not subscriptable

**Comment by yingkai1181** [comment]
btw, I have my 0.27.2 up and running for a few days and my site has 200-400 unique ips and they all tried and love the bot, I noticed this because a user messaged me about the bot disappeared, then I found out the project is gone lol 👍 

Luckily I have snapshot backup everyday lol

**Comment by EdwardBurgin** [comment]
We are experiencing something similar, server is resetting while being left alone, our error logs are different however: 
 File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data               
botfront-rasa             | httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method 
Botfront version: 0.27.5
![image](https://user-images.githubusercontent.com/442329/100225280-e0f67900-2f15-11eb-8ded-a8961495f527.png)

**Comment by yingkai1181** [comment]
@EdwardBurgin seems like db got hacked in my case
![微信图片_20201126085047](https://user-images.githubusercontent.com/72065027/100295423-89631680-2fc4-11eb-8340-72e79e7ca759.jpg)

**Comment by yingkai1181** [comment]
@EdwardBurgin @satishp962 I've closed port 27017 for weeks now, no more hacking or db reset, you guys can give it a try

**Comment by a7u7a** [comment]
Hi, I think I got a similar issue. I'm running botfront on a VM (following [this](https://botfront.io/docs/installation/server-cluster#single-server-installation-vm)) and I was working on a project where all of a sudden theUI took me back to the user creation screen. This is what the logs say:
```
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:17.785+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"185.220.100.241:26742","connectionId":14,"connectionCount":8}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:18.087+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn14","msg":"client metadata","attr":{"remote":"185.220.100.241:26742","client":"conn14","doc":{"driver":{"name":"PyMongo","version":"3.11.3"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.4.0-72-generic"},"platform":"CPython 3.8.5.final.0"}}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:18.626+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"185.220.101.208:31362","connectionId":15,"connectionCount":9}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:18.660+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"185.220.101.208:21882","connectionId":16,"connectionCount":10}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:18.851+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn15","msg":"client metadata","attr":{"remote":"185.220.101.208:31362","client":"conn15","doc":{"driver":{"name":"PyMongo","version":"3.11.3"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.4.0-72-generic"},"platform":"CPython 3.8.5.final.0"}}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:18.863+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn16","msg":"client metadata","attr":{"remote":"185.220.101.208:21882","client":"conn16","doc":{"driver":{"name":"PyMongo","version":"3.11.3"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.4.0-72-generic"},"platform":"CPython 3.8.5.final.0"}}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:19.586+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn15","msg":"Connection ended","attr":{"remote":"185.220.101.208:31362","connectionId":15,"connectionCount":9}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:19.657+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn14","msg":"Interrupted operation as its client disconnected","attr":{"opId":25597}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:19.660+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn14","msg":"Connection ended","attr":{"remote":"185.220.100.241:26742","connectionId":14,"connectionCount":8}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:19.829+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn16","msg":"Connection ended","attr":{"remote":"185.220.101.208:21882","connectionId":16,"connectionCount":7}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:26.610+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"23.129.64.236:50171","connectionId":17,"connectionCount":8}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:26.836+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn17","msg":"client metadata","attr":{"remote":"23.129.64.236:50171","client":"conn17","doc":{"driver":{"name":"PyMongo","version":"3.11.3"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.4.0-72-generic"},"platform":"CPython 3.8.5.final.0"}}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:27.276+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"23.129.64.236:52959","connectionId":18,"connectionCount":9}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:27.277+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"23.129.64.236:52957","connectionId":19,"connectionCount":10}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:27.525+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn18","msg":"client metadata","attr":{"remote":"23.129.64.236:52959","client":"conn18","doc":{"driver":{"name":"PyMongo","version":"3.11.3"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.4.0-72-generic"},"platform":"CPython 3.8.5.final.0"}}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:27.525+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn19","msg":"client metadata","attr":{"remote":"23.129.64.236:52957","client":"conn19","doc":{"driver":{"name":"PyMongo","version":"3.11.3"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.4.0-72-generic"},"platform":"CPython 3.8.5.final.0"}}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20337,   "ctx":"conn19","msg":"dropDatabase - starting","attr":{"db":"bf"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.analyticsDashboards"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.migrations"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.role-assignment"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.botResponses"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.examples"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.users"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.nlu_models"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.nlu_evaluations"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.forms"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.slots"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.endpoints"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.admin_settings"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.roles"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.projects"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.conversations"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.rolesData"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.form_results"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.storyGroups"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.credentials"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.activity"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.core_policies"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.stories"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.meteor_accounts_loginServiceConfiguration"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.156+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"bf","namespace":"bf.nlu_instances"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.392+00:00"},"s":"I",  "c":"COMMAND",  "id":20336,   "ctx":"conn19","msg":"dropDatabase","attr":{"db":"bf","numCollectionsDropped":24}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.392+00:00"},"s":"I",  "c":"COMMAND",  "id":51803,   "ctx":"conn19","msg":"Slow query","attr":{"type":"command","ns":"bf","command":{"dropDatabase":1,"lsid":{"id":{"$uuid":"3add8148-6638-46ea-89ec-abeee247d6d4"}},"$db":"bf","$readPreference":{"mode":"primary"}},"numYields":0,"reslen":54,"locks":{"ParallelBatchWriterMode":{"acquireCount":{"r":1}},"ReplicationStateTransition":{"acquireCount":{"w":1}},"Global":{"acquireCount":{"w":1}},"Database":{"acquireCount":{"W":1}},"Mutex":{"acquireCount":{"r":1}}},"flowControl":{"acquireCount":1,"timeAcquiringMicros":1},"storage":{},"protocol":"op_msg","durationMillis":236}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.638+00:00"},"s":"I",  "c":"COMMAND",  "id":20337,   "ctx":"conn19","msg":"dropDatabase - starting","attr":{"db":"config"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.638+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"config","namespace":"config.system.sessions"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.645+00:00"},"s":"I",  "c":"COMMAND",  "id":20336,   "ctx":"conn19","msg":"dropDatabase","attr":{"db":"config","numCollectionsDropped":1}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.891+00:00"},"s":"I",  "c":"COMMAND",  "id":20337,   "ctx":"conn19","msg":"dropDatabase - starting","attr":{"db":"local"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.892+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn19","msg":"dropDatabase - dropping collection","attr":{"db":"local","namespace":"local.startup_log"}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:28.895+00:00"},"s":"I",  "c":"COMMAND",  "id":20336,   "ctx":"conn19","msg":"dropDatabase","attr":{"db":"local","numCollectionsDropped":1}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:29.143+00:00"},"s":"I",  "c":"STORAGE",  "id":20320,   "ctx":"conn19","msg":"createCollection","attr":{"namespace":"READ__ME_TO_RECOVER_YOUR_DATA.README","uuidDisposition":"generated","uuid":{"uuid":{"$uuid":"3004e858-6245-4316-a60e-fed5ce2f88ed"}},"options":{}}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:29.155+00:00"},"s":"I",  "c":"INDEX",    "id":20345,   "ctx":"conn19","msg":"Index build: done building","attr":{"buildUUID":null,"namespace":"READ__ME_TO_RECOVER_YOUR_DATA.README","index":"_id_","commitTimestamp":{"$timestamp":{"t":0,"i":0}}}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:29.411+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn19","msg":"Connection ended","attr":{"remote":"23.129.64.236:52957","connectionId":19,"connectionCount":9}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:29.582+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn17","msg":"Interrupted operation as its client disconnected","attr":{"opId":25745}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:29.583+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn17","msg":"Connection ended","attr":{"remote":"23.129.64.236:50171","connectionId":17,"connectionCount":8}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:57:29.750+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn18","msg":"Connection ended","attr":{"remote":"23.129.64.236:52959","connectionId":18,"connectionCount":7}}
botfront-mongo | {"t":{"$date":"2021-05-04T01:58:00.052+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1620093480:52281][1:0x7f56b44a9700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 776, snapshot max: 776 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0)"}}
```
Did somebody come and dropped all my databases?
I have narrowed the allowed ports on the firewall. Any other ideas on why it happened and how to avoid this?

**Comment by oguzhankarahan** [comment]
Hi,

It looks like someone dropped the database. To prevent this, you can close the port 27017 (Mongodb port) on the server to outside. That way, there will be no problem.

Best regards,
