### ISSUE TITLE
Botfront-rasa constantly restarting 

### ISSUE THREAD

**Issue by JohnBat26** [botfront/botfront#862]
Hi
I try to start master branch of botfront for Rasa 2 compatibility.
All containers have started normally, except one: botfront-rasa.

This container constanly restarting because Docker file just run: rasa --help.
When I try to add:
```yml
command:
      - run
      - --enable-api
      - --debug
```
to .botfront/docker-compose-template.yml for botfront-rasa containerm when I get:
```
botfront-rasa | 2021-01-15 15:13:25 WARNING  rasa.utils.common  - Failed to write global config. Error: [Errno 13] Permission denied: '/.config'. Skipping.
botfront-rasa | Traceback (most recent call last):
botfront-rasa |   File "/opt/venv/bin/rasa", line 8, in <module>
botfront-rasa |     sys.exit(main())
botfront-rasa |   File "/opt/venv/lib/python3.8/site-packages/rasa/__main__.py", line 116, in main
botfront-rasa |     cmdline_arguments.func(cmdline_arguments)
botfront-rasa |   File "/opt/venv/lib/python3.8/site-packages/rasa/cli/run.py", line 81, in run
botfront-rasa |     set_endpoints_credentials_args_from_remote(args)
botfront-rasa |   File "/opt/venv/lib/python3.8/site-packages/rasa/utils/botfront.py", line 114, in set_endpoints_credentials_args_from_remote
botfront-rasa |     config = asyncio.get_event_loop().run_until_complete(
botfront-rasa |   File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
botfront-rasa |   File "/opt/venv/lib/python3.8/site-packages/rasa/utils/botfront.py", line 45, in get_config_via_graphql
botfront-rasa |     from sgqlc.endpoint.http import HTTPEndpoint
botfront-rasa | ModuleNotFoundError: No module named 'sgqlc'
```

In any cases botfront ui doesn't see Rasa backend and can't train a model :(.

Why is this happening since I run the default commands?

**Comment by JohnBat26** [comment]
And I have access problem to project folder because docker user can't write model after training and I have to invoke ```chmod 777 -R .``` :(

**Comment by pheel** [comment]
Hi @JohnBat26 in order to help, could you please post the entire content of your `.botfront/docker-compose-template.yml` file, and if using, `rasa/Dockerfile`?

**Comment by JohnBat26** [comment]
@pheel 
 - docker-compose-template.yml: https://gist.github.com/JohnBat26/7de4d11166ae0877761bb3100d7d48e4
 - Dockerfile:  https://gist.github.com/JohnBat26/6c09c55980ce91904ebc02524dbc0722

**Comment by pheel** [comment]
@JohnBat26 I'm guessing you built rasa-for-botfront using that Dockerfile? Do you have a reason not to use `botfront/rasa-for-botfront:v1.10.16-bf.4` or `botfront/rasa-for-botfront:v2.1.3-bf.7` from the Docker repository? You're still able to load custom packages using the `docker-compose-template.yml` file you linked: All you have to do is edit the contents `{PROJECT_DIR}/rasa`. If you really have to build rasa-for-botfront, you can build it from the `Dockerfile_botfront` Dockerfile. :)
