### ISSUE TITLE
Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero

### ISSUE THREAD

**Issue by phyx3r** [botfront/botfront#939]
**Describe the bug**
Cannot train after importing some botfront 0.27.5 stories.
The botfront interface shows this error after training:

```
Error: An unexpected error occurred during training. Error: reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero [[{{node cond_1/then/_75/cond_1/entities_sentence/SparseReshape}}]] [Op:__inference_train_on_batch_181872] Function call stack: train_on_batch
```

This is what I find in the `botfront logs`:

```
botfront-rasa | 2021-03-03 19:36:55 ERROR    rasa.server  - Traceback (most recent call last):
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/server.py", line 1021, in train
botfront-rasa |     training_result = await train_async(**training_payload)
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/train.py", line 178, in train_async
botfront-rasa |     finetuning_epoch_fraction=finetuning_epoch_fraction,
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/train.py", line 368, in _train_async_internal
botfront-rasa |     finetuning_epoch_fraction=finetuning_epoch_fraction,
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/train.py", line 431, in _do_training
botfront-rasa |     finetuning_epoch_fraction=finetuning_epoch_fraction,
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/train.py", line 626, in _train_core_with_validated_data
botfront-rasa |     model_to_finetune=model_to_finetune,
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/core/train.py", line 70, in train
botfront-rasa |     agent.train(training_data, **additional_arguments)
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/core/agent.py", line 726, in train
botfront-rasa |     training_trackers, self.domain, interpreter=self.interpreter, **kwargs
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/core/policies/ensemble.py", line 201, in train
botfront-rasa |     trackers_to_train, domain, interpreter=interpreter, **kwargs
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/core/policies/ted_policy.py", line 527, in train
botfront-rasa |     batch_strategy=self.config[BATCH_STRATEGY],
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/utils/tensorflow/models.py", line 242, in fit
botfront-rasa |     self.train_summary_writer,
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/utils/tensorflow/models.py", line 438, in _batch_loop
botfront-rasa |     call_model_function(batch_in)
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
botfront-rasa |     result = self._call(*args, **kwds)
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 807, in _call
botfront-rasa |     return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
botfront-rasa |     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
botfront-rasa |     cancellation_manager=cancellation_manager)
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
botfront-rasa |     ctx, args, cancellation_manager=cancellation_manager))
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
botfront-rasa |     ctx=ctx)
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
botfront-rasa |     inputs, attrs, num_outputs)
botfront-rasa | tensorflow.python.framework.errors_impl.InvalidArgumentError:  reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
botfront-rasa |          [[{{node cond_1/then/_75/cond_1/entities_sentence/SparseReshape}}]] [Op:__inference_train_on_batch_181872]
botfront-rasa | 
botfront-rasa | Function call stack:
botfront-rasa | train_on_batch
botfront-rasa | 
botfront-rasa | 
botfront-rasa | 2021-03-03 19:36:55 ERROR    rasa.server  - An unexpected error occurred during training. Error:  reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
botfront-rasa |          [[{{node cond_1/then/_75/cond_1/entities_sentence/SparseReshape}}]] [Op:__inference_train_on_batch_181872]
```

**To Reproduce**
Import attached stories and try to train.
[stories.zip](https://github.com/botfront/botfront/files/6078695/stories.zip)

**Server:**
 - OS: Ubuntu 18.04.5 LTS
 - Botfront Version 1.0.3

**Comment by brandaobrandisborges** [comment]
I had the same problem, and here is what I did:  
In order to understand where the problem was, I removed the last storie I had just created and trainned again, it worked.  
Then, I edited the story  
from:  
```
- or:
    - intent: my_first_intent
      entities: []
    - intent: my_sencond_intent
      user: An irrelevant phrase
      entities:
        - entity_name: An irrelevant entity
- action: my_action_form
- active_loop: my_action_form
- active_loop: null
- action: utter_some_bot_response
```
  
to:  
```
- or:
    - intent: my_first_intent
      entities: []
    - intent: my_sencond_intent
      entities: []
- action: my_action_form
- active_loop: my_action_form
- active_loop: null
- action: utter_some_bot_response
```

It worked!  
I'm running `botfront 1.0` on `centOS`, and the docker runs on `debian 10`

Hope it helps!

**Comment by phyx3r** [comment]
Thank you @brandaobrandisborges!
It worked!
