### ISSUE TITLE
botfront-rasa container always restarting with blueprint name error

### ISSUE THREAD

**Issue by materialausgabe** [botfront/botfront#952]
Hi,

today I change IP Address of my VM where botfront is running on.
I already updated botfront.yml and .env with new IP. And also did run "botfront up" afterwards.

Now I can see botfrint
In logs I see the botfront-rasa container always restarting with follwoing error:

botfront-rasa | 2021-03-10 16:37:35 DEBUG    rasa.utils.botfront  - Trying to fetch config from http://botfront:3000/graphql (retry #1)
botfront-rasa | Traceback (most recent call last):
botfront-rasa |   File "/opt/venv/bin/rasa", line 8, in <module>
botfront-rasa |     sys.exit(main())
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/__main__.py", line 116, in main
botfront-rasa |     cmdline_arguments.func(cmdline_arguments)
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/cli/run.py", line 94, in run
botfront-rasa |     rasa.run(**vars(args))
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/run.py", line 57, in run
botfront-rasa |     **kwargs,
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/core/run.py", line 187, in serve_application
botfront-rasa |     conversation_id=conversation_id,
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/core/run.py", line 116, in configure_app
botfront-rasa |     channels.channel.register(input_channels, app, route=route)
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/core/channels/channel.py", line 92, in register
botfront-rasa |     app.blueprint(channel.blueprint(handler), url_prefix=p)
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/sanic/app.py", line 744, in blueprint
botfront-rasa |     "Blueprint names must be unique." % (blueprint.name,)
botfront-rasa | AssertionError: A blueprint with the name "socketio_webhook" is already registered.  Blueprint names must be unique.

Any idea?

Regards,

M

**Comment by materialausgabe** [comment]
Hi,

in the ,eantime I have found out that error is not related to changed IP Address.
It is related to credentials setting of my project. When I remove 

rasa_addons.core.channels.webchat.WebchatInput:
  session_persistence: true
  base_url: 'http://localhost:5005'
  socket_path: /socket.io/
rasa_addons.core.channels.bot_regression_test.BotRegressionTestInput: {}

from config then botront-rasa container starts successfully.
On the other side the Chat feature disappears from Botfront GUI.

**Comment by materialausgabe** [comment]
Hi,
in the meantime I found the issue. Like often it was sitting in front of the screen.
I had an error in my credentials settings.
Thanks.
M
