### ISSUE TITLE
Weird rasa crash with a specific time dimension (Duckling)

### ISSUE THREAD

**Issue by WeberJulian** [botfront/botfront#994]
I'm trying out the API tab in the nlu part of botfront ui.

A specific time dimension "interval" makes rasa-for-botfront crash:
For the sentence "last three days" I get this error:

```
botfront-app | 2021-03-30T14:51:20.975Z [error] : POST at /model/parse failed at response time user: 9a2jTLrvi59rpBQJK /imports/api/instances/instances.methods.js - rasa.parse with {"instance":{"_id":"4WT6rZ72GdGzHyXyr","name":"Default Instance","host":"http://rasa:5005","projectId":"qGmLZ3XyYXhxKvaf6"},"examples":[{"text":"last 3 days","lang":"en"}]} url: /model/parse  data: "{\"text\":\"last 3 days\",\"lang\":\"en\"}" error: Error: Request failed with status code 500
botfront-rasa | 2021-03-30 14:51:20 DEBUG    rasa.server  - Traceback (most recent call last):
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/server.py", line 1292, in parse
botfront-rasa |     data.get("text"), lang=request.json.get("lang"),  # bf
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/core/agent.py", line 509, in parse_message_using_nlu_interpreter
botfront-rasa |     return await processor.parse_message(message, tracker)
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/core/processor.py", line 551, in parse_message
botfront-rasa |     text, message.message_id, tracker, metadata=message.metadata
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa_addons-2.2.5.4-py3.7.egg/rasa_addons/core/interpreter.py", line 38, in parse
botfront-rasa |     return await interpreter.parse(text)
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 149, in parse
botfront-rasa |     result = self.interpreter.parse(text)
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/nlu/model.py", line 454, in parse
botfront-rasa |     component.process(message, **self.context)
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa_addons-2.2.5.4-py3.7.egg/rasa_addons/nlu/components/intent_ranking_canonical_example_injector.py", line 83, in process
botfront-rasa |     intent_ranking[i].get("name"), entities
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa_addons-2.2.5.4-py3.7.egg/rasa_addons/nlu/components/intent_ranking_canonical_example_injector.py", line 64, in get_canonical
botfront-rasa |     entities = self.generate_entity_pairs(entities)
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa_addons-2.2.5.4-py3.7.egg/rasa_addons/nlu/components/intent_ranking_canonical_example_injector.py", line 35, in generate_entity_pairs
botfront-rasa |     return frozenset((e.get("entity"), e.get("value")) for e in entities)
botfront-rasa | TypeError: unhashable type: 'dict'
botfront-rasa | 
botfront-rasa | During handling of the above exception, another exception occurred:
botfront-rasa | 
botfront-rasa | Traceback (most recent call last):
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/server.py", line 1299, in parse
botfront-rasa |     f"An unexpected error occurred. Error: {e}",
botfront-rasa | rasa.server.ErrorResponse
botfront-rasa | 
botfront-rasa | 2021-03-30 14:51:20 ERROR    rasa.server  - An unexpected error occurred. Error:
```

The sentences "last three da" or "it's 10 o'clock" work fine

I also tried calling duckling directly and it works fine:

```
curl -XPOST http://0.0.0.0:8000/parse --data 'locale=en_GB&text=last three months'
[{"body":"last three months","start":0,"value":{"values":[{"to":{"value":"2021-03-01T00:00:00.000-08:00","grain":"month"},"from":{"value":"2020-12-01T00:00:00.000-08:00","grain":"month"},"type":"interval"}],"to":{"value":"2021-03-01T00:00:00.000-08:00","grain":"month"},"from":{"value":"2020-12-01T00:00:00.000-08:00","grain":"month"},"type":"interval"},"end":17,"dim":"time","latent":false}]
```

**Comment by WeberJulian** [comment]
It seems like rasa merged a PR to support intervals in 2017 https://github.com/RasaHQ/rasa/pull/686

**Comment by WeberJulian** [comment]
maybe we can handle from and to values from the interval as tuples (from, to) so that the value is hashable, but then we stray away from the rasa implementation...
